version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-galeria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: galeriadb
      MYSQL_USER: galeriauser
      MYSQL_PASSWORD: galeriapassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-galeria-data:/var/lib/mysql

  app:
    build: .
    container_name: galeria-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/galeriadb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: galeriauser #confirmar
      SPRING_DATASOURCE_PASSWORD: galeriapassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql-galeria-data: